### ISSUE TITLE
Unable to load new content at the moment...

### ISSUE THREAD

**Issue by bitcoinuser** [PrimalHQ/primal-android-app#100]
Hi,

Sometimes when I minimize Primal for a long time then I restore it, show this message: Unable to load new content at the moment...

![photo_5130086454091951044_y](https://github.com/PrimalHQ/primal-android-app/assets/1178856/7a13a0f0-4e4e-43de-91f3-02f04e114182)

**Comment by bitcoinuser** [comment]
But If I close and open Primal again, the message disappear and show new notes.

**Comment by AleksandarIlic** [comment]
Its not a bug, it means that the app couldnt load notes at that moment - 2nd line shows the error message. As soon as the app succeeds to get recent notes, it removes the error.

The question is if we should show the error message or silently ignore and not show anything.

**Comment by bitcoinuser** [comment]
> The question is if we should show the error message or silently ignore and not show anything.

Show a message like "loading new content"?

**Comment by bitcoinuser** [comment]
> As soon as the app succeeds to get recent notes, it removes the error.

In my experience I always needed to restart Primal to the message disappear and show new notes.

**Comment by AleksandarIlic** [comment]
This is an error message. App tried loading new content and couldnt reach the api 3 times in a row. Now app waits next sync cycle in 25-35 secs. When you exit/enter you restart the sync cycles from the start.

I want to implement pull to refresh first before making any further changes to the feed sync. Except pagination issue which is still blocked by backend.

Retry button with the error message might also be the solution.

**Comment by bitcoinuser** [comment]
I'm not seeing this anymore. If I reproduce again, I can reopen.
