### ISSUE TITLE
Links in profiles that don't start with https:// don't open

### ISSUE THREAD

**Issue by rottenwheel** [PrimalHQ/primal-android-app#104]
When tapping on links such as designwithcarter.com vs. https://rottenwheel.com/, former displays a pop-up message: 'App not found that could open designwithcarter.com'

On latest Primal Android release go to Carter's profile (npub1p3j8q3u4l0lddrhj9yumju0lnrj0kdhtalgh96l86a8gkln5kj6qdwnh6z) and try opening the link in bio, you'll get the pop-up message seen in screenshot below.

![image](https://github.com/PrimalHQ/primal-android-app/assets/92872541/aa2284dc-bf26-4356-9839-cb978c1b4877)

On the other hand, if you pull up my profile (npub164xgt7nysd3euvrdk0h6p7xxhulhnjnpmu0utzau86wf6859qn6srac0qx), that contains the https://, it opens the link in your system's browser just fine.

**Comment by AleksandarIlic** [comment]
This was fixed in 0.96. Please retest.
