### ISSUE TITLE
Unable to update Primal via Obtanium

### ISSUE THREAD

**Issue by davotoula** [PrimalHQ/primal-android-app#115]
## Describe the bug
Unable to update Primal via Obtanium 

### Steps to reproduce
Click update in Obtanium 

### Expected behavior
Downloads and installs 

### Additional context
Download successful but fails to install

![Screenshot_20240329-173854.png](https://github.com/PrimalHQ/primal-android-app/assets/1747287/e0521805-461e-4b56-8f5e-ee8010b99f56)

**Comment by AleksandarIlic** [comment]
How did you installed previous build which wont update?

**Comment by davotoula** [comment]
I think it was through Obtanium as well but not sure. Sorry.

Unistalling and reinstalling through Obtanium worked.

Not even sure whether this is an Obtanium or a primal bug.

What is the second "crash report" apk for?

**Comment by AleksandarIlic** [comment]
Google Play signs with its own certificate so updates wont work between apk and play releases.

And they are different builds. Play build has play libs while apk is aosp and can work without play services.

Crash reporting apk is the aosp build with Primal's very simple crash reporting tool which submits stacktraces in case of crashes. On other builds this is disabled.
