### ISSUE TITLE
More than 2 hours without new notes

### ISSUE THREAD

**Issue by bitcoinuser** [PrimalHQ/primal-android-app#124]
Hi,

More than 2 hours without new notes, even with pull refresh.

![Screenshot_2024-04-16-14-06-34-697_net primal android](https://github.com/PrimalHQ/primal-android-app/assets/1178856/326d5da6-000a-4e16-b86e-bfd9f3d3e0fb)

**Comment by bitcoinuser** [comment]
See the error: Remote key not found.

**Comment by vcavallo** [comment]
Me too

**Comment by vcavallo** [comment]
https://github.com/PrimalHQ/primal-android-app/issues/100

This current issue seems to be distinct from the one above, because quitting the app and reopening it doesn't fix it. There are definitely new notes to be fetched because I'm getting them in Amethyst (and noscl, etc).

**Comment by vcavallo** [comment]
@bitcoinuser I've been DMing on nostr with marko@primal.net and he sent me an updated .apk that solves this problem. Not sure when it'll be pushed out, but it seems the fix is immanent.

**Comment by bitcoinuser** [comment]
> @bitcoinuser I've been DMing on nostr with [marko@primal.net](mailto:marko@primal.net) and he sent me an updated .apk that solves this problem. Not sure when it'll be pushed out, but it seems the fix is immanent.

Great. I will wait the official update.
