### ISSUE TITLE
Clicking on profile photos in message window should open the profiles people pages

### ISSUE THREAD

**Issue by bitcoinuser** [PrimalHQ/primal-android-app#126]
Hi,

Clicking on profile photos in message window should open the profiles people pages. For now when I click in a profile photo in message window, nothing happens.

Obs. in the feed window, when I click on profiles photos, works ok, open the person profile page.

Thanks.

**Comment by AleksandarIlic** [comment]
Just fixed this. It will be released with the next release, 0.99.X.

**Comment by bitcoinuser** [comment]
Fixed.
