### ISSUE TITLE
Missing a note in notification window

### ISSUE THREAD

**Issue by bitcoinuser** [PrimalHQ/primal-android-app#135]
Hi, 

Someone replied a note I posted but I don't see this reply in my notification window. 
https://primal.net/e/note1ue8yl09nc7txvnxk6rf0jcl4lsyeyxlykqdhkd594sw9zvmey7wqg8pfjh

The reply from Rice user:

![photo_5001297118077497037_y](https://github.com/PrimalHQ/primal-android-app/assets/1178856/d8aa9958-47e0-4485-857d-d3641509fbb2)

**Comment by AleksandarIlic** [comment]
If any notifications are missing and not showing up even after few minutes then this is a caching issues. You should open a ticket then on the primal-caching-service git repo.

**Comment by bitcoinuser** [comment]
Ok, thanks.
