### ISSUE TITLE
If I click on a note then click on Android back button, should go to the same position I was

### ISSUE THREAD

**Issue by bitcoinuser** [PrimalHQ/primal-android-app#14]
## Describe the bug
If I click on a note then click on Android back button, should go to the same position I was. The way works now, always go to the top

### Steps to reproduce
Scroll down on feed, click in a note, then click android back button

### Expected behavior
Go to the same position on feed that I was.

### Environment
 - Details that you think may affect.

**Comment by AleksandarIlic** [comment]
Thank you @bitcoinuser for the report.

We are aware of this issue only for the notes which are a bit down on the feed (40-50+ notes) and the cause is the bug in the library that app is using. 

Do you experience this bug also for the first notes on the feed?

**Comment by bitcoinuser** [comment]
> Do you experience this bug also for the first notes on the feed?

Sometimes yes, sometimes no. See the video.


https://github.com/PrimalHQ/primal-android-app/assets/1178856/64de2970-1083-40b0-9530-dbd0d3d35cec

**Comment by AleksandarIlic** [comment]
@bitcoinuser It's fixed in the latest 0.15.1 build. Please reopen if it doesn't work on your device.
