### ISSUE TITLE
Primal always crashing on search window when selecting the search field

### ISSUE THREAD

**Issue by bitcoinuser** [PrimalHQ/primal-android-app#145]
Hi,

Primal always crashing on search window when selecting the search field.

https://github.com/PrimalHQ/primal-android-app/assets/1178856/193446ad-3ff4-4f67-af6e-374a0bfa312f

**Comment by davotoula** [comment]
I can't reproduce that using latest 0.99.2

Have you tried some basics things one at a time?

- Install latest version of Primal
- Delete cache
- Re-install Primal
- Backing up your nsec and logging in with a different user
- Any third party apps install, especially keyboards and/or auto fillers

**Comment by bitcoinuser** [comment]
> I can't reproduce that using latest 0.99.2

I reproduce this in 0.99.2

**Comment by davotoula** [comment]
what a about

- Delete cache
- Re-install Primal
- Backing up your nsec and logging in with a different user
- Any third party apps install, especially keyboards and/or auto fillers

??

**Comment by bitcoinuser** [comment]
Here crash too:


https://github.com/PrimalHQ/primal-android-app/assets/1178856/7e017dbf-5aa6-4119-8da1-bd99ef635001

**Comment by bitcoinuser** [comment]
When crashing it shows this:

![Screenshot_2024-05-10-18-18-55-199_com miui bugreport](https://github.com/PrimalHQ/primal-android-app/assets/1178856/440e0a5d-b29c-4a8f-9473-345c556f1d9e)

**Comment by AleksandarIlic** [comment]
Thanks! I'll fix it.

**Comment by bitcoinuser** [comment]
> Thanks! Fixed in 0.99.3+.

Hum, strange, fixed here without need to update Primal. Maybe a server thing fix?

**Comment by AleksandarIlic** [comment]
It's not related to the server. Recent users are shown before recommended users. If you open any of the recommended users, that user will become recent user; and then if you open search the app crashes because there should be only one user.
