### ISSUE TITLE
Crash on search 

### ISSUE THREAD

**Issue by bitcoinuser** [PrimalHQ/primal-android-app#153]
Hi, if you paste and search for this: npub10y3:js in the search window, primal will crash.

![Screenshot_2024-05-14-02-39-50-095_com miui bugreport](https://github.com/PrimalHQ/primal-android-app/assets/1178856/32e44d7a-38a2-4b9d-a6b4-69f54ccd073f)

**Comment by AleksandarIlic** [comment]
Thanks. It will be fixed in the next release.

**Comment by bitcoinuser** [comment]
Fixed
