### ISSUE TITLE
Why now I need to click on new notes to load the new notes?

### ISSUE THREAD

**Issue by bitcoinuser** [PrimalHQ/primal-android-app#158]
Hi @AleksandarIlic Why now I need to click on new notes to load the new notes? I like the old way where shows the new notes button, but I could just scroll down to see the new notes, without needing to click on new notes button to load it.

Thanks.

**Comment by AleksandarIlic** [comment]
We had to change the approach to avoid gaps in the feed. Fixing gaps and being able to scroll forwards (as before) at the same time has many edge cases and we can't provide both at the moment.
