### ISSUE TITLE
Primal always crash when we lock the phone with Primal opened and we unlock after like 30 minutes and wait on main Primal window without doing any action until crash

### ISSUE THREAD

**Issue by bitcoinuser** [PrimalHQ/primal-android-app#159]
Hi,

Primal always crash when we lock the phone with Primal opened and we unlock after like 30 minutes and wait on main Primal window without doing any action until Primal crash.

Are you able to reproduce @AleksandarIlic

**Comment by AleksandarIlic** [comment]
I was unable to reproduce this crash. 

Which version this happened? Which device and OS version?

**Comment by bitcoinuser** [comment]
> I was unable to reproduce this crash.
> 
> Which version this happened? Which device and OS version?

Not always crash, so not easily reproducible.
