### ISSUE TITLE
Add an option on settings to always show the bottom bar and top bar

### ISSUE THREAD

**Issue by bitcoinuser** [PrimalHQ/primal-android-app#16]
## Summary
Add an option on settings to always show the bottom bar and top bar.

I don't like this thing that hide the bottom and top bar when we scroll the feed. So I think this should be optional.

Thanks.

**Comment by AleksandarIlic** [comment]
It's on the list.

In the meantime you can long-press on feed title on Home tab and it will toggle on/off focus mode. The change is saved per session and once app gets killed (by user or system) it will revert to default.

**Comment by bitcoinuser** [comment]
Fixed.
