### ISSUE TITLE
Crash when scrolling the feed

### ISSUE THREAD

**Issue by bitcoinuser** [PrimalHQ/primal-android-app#160]
Crash when scrolling the feed

![Screenshot_2024-06-21-09-03-21-155_com miui bugreport](https://github.com/PrimalHQ/primal-android-app/assets/1178856/19939bf0-691e-4d09-a95d-9537dd928722)

**Comment by AleksandarIlic** [comment]
Can you try to reproduce it with following build:
https://drive.proton.me/urls/VAZWRH29MG#1kvPKw92Maqw

It should be fixed in this build.

**Comment by bitcoinuser** [comment]
I don't know how to reproduce these crashs. So I will close these issues.
