### ISSUE TITLE
Bookmarks is not working for me anymore 

### ISSUE THREAD

**Issue by bitcoinuser** [PrimalHQ/primal-android-app#161]
Hi,

Bookmarks is not working for me anymore . I restarted Primal and same problem.

![Screenshot_2024-06-21-09-17-00-647_net primal android](https://github.com/PrimalHQ/primal-android-app/assets/1178856/3cf1407e-1be0-4102-9e89-9a7466e58978)

**Comment by bitcoinuser** [comment]
> @bitcoinuser Can you check again? It works on my devices, maybe it was a backend problem.

For me doesn't work. I tried many times, many days.


![Screenshot_2024-06-27-10-52-57-244_net primal android](https://github.com/PrimalHQ/primal-android-app/assets/1178856/225f9870-c167-49b9-bea2-7b8bb02a2952)

**Comment by AleksandarIlic** [comment]
@bitcoinuser It was a backend issue. Fixed now.

**Comment by bitcoinuser** [comment]
Fixed
