### ISSUE TITLE
Sign up button doesn't work & app crashes scrolling down the feed.

### ISSUE THREAD

**Issue by Git-Forked** [PrimalHQ/primal-android-app#29]
## Describe the bug
Sign up button doesn't work & app crashes scrolling down the feed. 
Had to sign up from another app because this one the button does not do anything when clicked. 
After signing in with key created from another web app, this app crashes instantly every time I attempt to scroll down the feed.

### Steps to reproduce
for bug 1: Install app and click sign up button.
for bug 2: Sign in with a key from elsewhere and attempt to scroll down the feed.

### Expected behavior
for bug 1: I would expect to click the sign up button and be able to create an account.
for bug 2: I would expect to be able to scroll down the feed.

### Environment
Running on Android 10

**Comment by AleksandarIlic** [comment]
The sign up button is not yet implement. We will probably disable it or remove it to avoid misleading expectations until is implemented.

Could you please crash the app few times with the 0.14.3-crash-report build so we could get the error report? Build can be found on the Release page of this repository.

**Comment by Git-Forked** [comment]
Downloaded and installed, and crashed it a few times.  
Where do I find the crash report to submit?

**Comment by AleksandarIlic** [comment]
The crash report is submitted automatically. We already got them and we'll look into them. Thank you!

**Comment by Git-Forked** [comment]
Thank you. 
I look forward to the progress of this app.

**Comment by AleksandarIlic** [comment]
@Git-Forked The crash when scrolling down the feed has been fixed in 0.15.2. Since the sing-up button is not yet implemented, I'm closing this ticket. Please reopen if you are still experiencing feed crashes on the 0.15.2 build.
