### ISSUE TITLE
When i sign out and click sign it crashes

### ISSUE THREAD

**Issue by DLRAM** [PrimalHQ/primal-android-app#4]
I am using lastest version

**Comment by AleksandarIlic** [comment]
@DLRAM Does it crash all the time when you sign out and click sign in?

**Comment by DLRAM** [comment]
Now it is not crashing when signing in. Before, every time I clicked 'sign in,' it crashed.

**Comment by DLRAM** [comment]
Why can't I like or comment on the post?I am using a private nostr key

**Comment by AleksandarIlic** [comment]
Great to hear that is working. In case login crashes resurfaces, please do `Clear Data` for App Info settings. We are still in the early phase of sometimes there are breaking changes in the updates.

Build 0.11 was read-only. Today we just released 0.12 build which supports simple write operations (like, repost, new post and commenting). Check it out!
