### ISSUE TITLE
Some users are not able to sign in with their nsec

### ISSUE THREAD

**Issue by mbrat1** [PrimalHQ/primal-android-app#5]
Some users have reported that they are not able to sign in with their nsec. 

### Additional context
Example of such a user report: 
https://primal.net/thread/note1q39t2ucl73jtx4faymc5w4vqjefrqwstqqg28sak53p0y0lqxtjq0ugflj

**Comment by AleksandarIlic** [comment]
With 0.12+ builds we are trimming text from clipboards. I assume this was the issue. Additionally with 0.12.4+ builds we are no longer accepting any whitespace at all in nsec input field.
