### ISSUE TITLE
Add image click to enlarge/zoom.

### ISSUE THREAD

**Issue by Cancerboyuofa** [PrimalHQ/primal-android-app#54]
## Summary
Add a simple image clickability to be able to view full screen and/or zoom in.

### Motivation
Images on phone are too small many times, especially memes. Having the ability to click to view the image/enlarge it, and possibly make the option to then zoom in on the image would benefit all useres. Not an issue on web version, but android for sure.

**Comment by AleksandarIlic** [comment]
We implemented media gallery which has zooming capabilities. You can try the latest builds if you already haven't seen it.
