### ISSUE TITLE
The top bar in thread window shouldn't collapse when scroll the feed.

### ISSUE THREAD

**Issue by bitcoinuser** [PrimalHQ/primal-android-app#61]
Hi,

The top bar in thread window shouldn't collapse when scroll the feed. In X app the top bar do not collapse, but in Primal yes, see the video:

https://github.com/PrimalHQ/primal-android-app/assets/1178856/dffd8e56-53b7-49fa-8f3e-7f2572f4867b

**Comment by AleksandarIlic** [comment]
Just fixed it. It will be available in 0.95.1+ builds.
