### ISSUE TITLE
Clicking on X to close the post window, the keyboard doesn't close smoothly 

### ISSUE THREAD

**Issue by bitcoinuser** [PrimalHQ/primal-android-app#62]
Hi,

Clicking on X to close the post window, the keyboard doesn't close smoothly. See the video.

https://github.com/PrimalHQ/primal-android-app/assets/1178856/6342996f-50a8-486d-b557-84016f341660

**Comment by AleksandarIlic** [comment]
Closing the ticket. Please reopen if necessary.
