### ISSUE TITLE
No relays found

### ISSUE THREAD

**Issue by Koenig-Johannes** [PrimalHQ/primal-android-app#64]
## Describe the bug
Im already using Primal Web on desktop and wanted to use it on mobile too. after entering Nsec i cant post and only get a Massage: "No relays found. Please configure your Network" but i don't find a way to configure anything.

### Steps to reproduce
Gogle Pixel 6a with grapheneOS
Install Primal and insert Nsec

### Expected behavior
there should be a way to configure Relays. "Network" is not part of the setting menue.

**Comment by Wyckoffan** [comment]
I have the same issue, I can retrieve post but when sending "no relays found" error pops up.
I am using Pixel 8 Graphehe OS.

**Comment by AleksandarIlic** [comment]
We are yet to support NIP-65 which is causing the problem. If account is using contacts list to save the relays everything works fine.

Supporting NIP-65 and implementing "Network" settings is on the backlog; I'm expecting to start working on it in the next week or two.

**Comment by bitcoinuser** [comment]
Is this fixed?

**Comment by AleksandarIlic** [comment]
There should be no more "relays not found" in the app. We implemented NIP-65 support in the app. Please open new issue for relays related bug.
