### ISSUE TITLE
cleartext traffic?

### ISSUE THREAD

**Issue by IzzySoft** [PrimalHQ/primal-android-app#67]
My scanner just received an upgrade, and today reported on your updated APK:

```
! repo/net.primal.android_80.apk declares flag(s): usesCleartextTraffic
! repo/net.primal.android_80.apk declares risky permission(s): android.permission.CAMERA
```

While camera access was easy to figure (QR code scanner): does primal really use unencrypted connections (like HTTP instead of HTTPS)?

**Comment by AleksandarIlic** [comment]
Primal is using HTTPS and WSS. 

The flag `usesCleartextTraffic` was enabled in this commit https://github.com/PrimalHQ/primal-android-app/commit/73333c3c because there are many images in notes which are using `http` links.

Do you have any suggestions how to handle this http links from notes better?

**Comment by AleksandarIlic** [comment]
Yes! Primal Android app needs access to camera for QR code scanning. At the moment, we are using camera only in Primal Wallet and in the up-coming weeks/months we plan to add support for scanning nostr profile QR codes as well. 

This is our camera permission rational displayed to the users:
`<string name="qrcode_scanner_permission_rationale">Primal needs access to your camera to scan QR codes.</string>`

We are using `zbar` native library for QR code detection on purpose to avoid use of Google ML libraries. And speaking of Google, we have two product flavours `google` and `aosp`. The main difference is that in `google` flavour we have integrated Google Play Billing lib because of in-app purchase (for sats in wallet), while the `aosp` flavour is free of Google.

I see that you are part of F-Droid organisation - do you plan to add Primal Android app on F-Droid?

**Comment by IzzySoft** [comment]
> I see that you are part of F-Droid organisation - do you plan to add Primal Android app on F-Droid?

No, not that – I'm currently [not active at F-Droid](https://gitlab.com/fdroid/admin/-/issues/447), and it doesn't look like that will change soon. Your app is listed [in my repo](https://apt.izzysoft.de/packages/net.primal.android/), which has some enhancements you won't find on F-Droid (see e.g. [here](https://apt.izzysoft.de/fdroid/index/info) and, for the latest enhancements, [here](https://gitlab.com/IzzyOnDroid/repo/-/issues/475)). So if you have any questions on that, feel free to ask!

And should you want another question/suggestion from me: how about establishing Fastlane structures, so you can maintain your app's description, graphics etc. and my updater pulls them along with each release? Be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance with that. And to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link to your app's presence in my repo, e.g. from the README :smiley:

Thanks for your help! All "red flags" have been cleared now (both above items have been added to your app's allow-list here, together with their explanation), so this issue is solved. Feel free to ping me from another one e.g. with Fastlane; if you wish, I can provide you what is set up here via PR as a starter package for that.

**Comment by AleksandarIlic** [comment]
Thanks for the clarification. Do you use the provided APK from the release page or are you building the app from the source?  My main concerns is that only officially released builds/versions (available on releases page) are published to other stores such as yours or F-Droid. We don't want intermediate alpha builds to end-up publicly available to avoid breaking-changes (which happens often on alpha builds).

We are currently in need for setting up a publishing process `aosp` builds on F-Droid; we had dozens of requests for that already. If the process is the same for your repo and F-Droid, maybe you could help us to setup for both of them?

**Comment by IzzySoft** [comment]
> Thanks for the clarification.

Gladly!

> Do you use the provided APK from the release page

Yes.

> only officially released builds/versions (available on releases page) are published to other stores such as yours or F-Droid

That's what happens with my repo. For F-Droid this would require establishing reproducible builds.

> We don't want intermediate alpha builds to end-up publicly available

Full ack! With very few exceptions (where my repo explicitly hosts "test builds" and the app description or name/title make that clear, I don't want such things to enter my repo either :wink:)

> If the process is the same for your repo and F-Droid

No, the process is different. I just pick the APKs "provided officially" (and apply a bunch of tests on them to make sure as best as I can they are "good"), F-Droid insists on building from source themselves.

What I however could help you with is establishing Fastlane structures (which F-Droid will want in your app's repo, too) – by opening a PR with what is currently set up with my repo for the very same purpose. You could then build upon that "starter package" and use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for reference.

**Comment by AleksandarIlic** [comment]
Great! Sure, let's do it like that. Thanks!

**Comment by IzzySoft** [comment]
Done – your turn now :smiley:

**Comment by AleksandarIlic** [comment]
Merged, thanks! Can you point me what are the next stops to get the build visible in F-Droid as well?

**Comment by IzzySoft** [comment]
> Merged, thanks!

Gladly! Unfortunately I messed that one up a little (opened another PR to fix that, which then somehow included one of your commits despite me pulling main first afresh, no idea…)

> Can you point me what are the next stops to get the build visible in F-Droid as well?

For F-Droid.org?

* [Quick path to get your app into F-Droid](https://gitlab.com/-/snippets/1896503#quick-path-to-get-your-app-into-f-droid)
* [the process of integrating an app with F-Droid](https://android.izzysoft.de/articles/named/fdroid-intro-2#rfp)

**Comment by IzzySoft** [comment]
Sorry to bother you again. All new features on my scanner are now enabled, so more things show up:

* `android.permission.READ_EXTERNAL_STORAGE*`: The `*` states this permission was granted implicitly as `WRITE_EXTERNAL_STORAGE` is requested. Can you please let me know what for these two are needed? The app description is still a bit short and gives no clue :wink:
* `DEPENDENCY_INFO_BLOCK` was found in your signing blocks. That's an encrypted BLOB only Google can read.

Remedy for the latter:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

**Comment by AleksandarIlic** [comment]
Hey @IzzySoft, 

In the latest release we added a feature to Save Image to device. The entire feature was implemented in this commit fb9849b7dc9843c11d0aa417d88502f2592d322a. I had to add permission "WRITE_EXTERNAL_STORAGE" to be able to do this on devices up to SDK 28. You can check `MediaDownloader` to see what are we actually doing when writing.

Regarding READ_EXTERNAL_STORAGE, we don't use that at all. The only reading from device we do is when attaching a picture to a Note/Post, but this was implemented and released months ago.

I was not aware of 'DEPENDENCY_INFO_BLOCK' before; And not sure why is included now in the builds. Maybe because the project was upgraded to AGP 8.2.2. I'll add your snippet to `build.gradle` to disable the BLOB for the next releases.

**Comment by IzzySoft** [comment]
> a feature to Save Image to device

Thanks! That explains, and thus justifies. Though as the minimum Android version you support is 8.0, wouldn't SAF (Storage Access Framework) suffice for that? That is, unless you want to save to some media or download directory. But it looks like you already checked that and something didn't work (or the library used for that requires it)?

> Regarding READ_EXTERNAL_STORAGE, we don't use that at all.

If you want to get rid of it, you can use `tools:node` in your `AndroidManifest.xml` to achieve that – see [Removing Unwanted Manifest Permissions With tools:node](https://developermemos.com/posts/removing-unwanted-manifest-permissions/). Should removing the permission turn out to have side-effects, I'd simply add it to the allow-list here with your proper explanation.

> I was not aware of 'DEPENDENCY_INFO_BLOCK' before

Few are.

> And not sure why is included now in the builds.

It was probably there all along. It just turned up here now that I added a check for that. Android Studio and IntelliJ IDEA (maybe more, but for those 2 I know) add it automatically when signing. So the above block for your `build.gradle` tells them not to. Or you use `apksigner` for signing which generally doesn't include that.

> I'll add your snippet to `build.gradle` to disable the BLOB for the next releases.

Wonderful, thanks! :star_struck:

**Comment by IzzySoft** [comment]
Oof. Today's report has:

```
! repo/net.primal.android_98.apk declares sensitive permission(s):
  android.permission.READ_PHONE_STATE android.permission.READ_EXTERNAL_STORAGE*
```

So now `READ_PHONE_STATE` was added to the list. Can you please tell me what for?

**Comment by AleksandarIlic** [comment]
I dont remember adding that or using it at all. I'll investigate.

**Comment by AleksandarIlic** [comment]
I have upgraded compose and some other libs and some of them has added the permission.

I'll remove it manually just like we did for the READ_EXTERNAL_STORAGE.

Thanks for reporting it.

**Comment by AleksandarIlic** [comment]
Thanks for your reports. Keep them coming!
