### ISSUE TITLE
Rewrite with dart/flutter?

### ISSUE THREAD

**Issue by trymeouteh** [PrimalHQ/primal-android-app#68]
This is a great app and I am only suggesting rewriting the app with dart/flutter to allow the app to be compilled and released for mobile and desktop.

Flutter allows you to create apps for Windows, MacOS, Linux, Android and iOS. More devices, more users using nostr and all done with one codebase to manage.

**Comment by AleksandarIlic** [comment]
Thanks for the suggestion. We'll consider this if we decide at some point to rewrite the apps.
