### ISSUE TITLE
Single tap zap doesn't send custom sat amount

### ISSUE THREAD

**Issue by juliancoronado** [PrimalHQ/primal-android-app#70]
## Describe the bug
In the Primal app, changing the single tap zap value doesn't actually send the custom value. I set my single tap zap to 21 sats, however tapping a note to zap it still sends 42 sets (the original value).

### Steps to reproduce
Change the single tap value in Primal Zap settings to a new number of sats. Test out zapping a note and compare how many sats were sent to the custom value you set in the Settings.

### Expected behavior
The user set value of single tap zaps should be the amount of sats sent when the user taps the zap button on a note.

### Environment
 I'm on the latest version of Primal from the Play Store - 0.90.2

**Comment by AleksandarIlic** [comment]
Thanks for reporting the bug. This was fixed 3 days ago in 765461a2cd3ba88b61907b17bacd51d230d41e3b and it will be released this week.

**Comment by juliancoronado** [comment]
This issue is now fixed the latest release 0.91.2

**Comment by juliancoronado** [comment]
This issue is now fixed the latest release 0.91.2
