### ISSUE TITLE
Zap never works for me

### ISSUE THREAD

**Issue by bitcoinuser** [PrimalHQ/primal-android-app#75]
Hi, 

Zap never works for me. See the video:

https://github.com/PrimalHQ/primal-android-app/assets/1178856/df47d348-bceb-45e2-9fe0-2c02d959c5f3

**Comment by AleksandarIlic** [comment]
This message is shown if following statement is `true`:
```        
if (userRelays.isNullOrEmpty() || nostrZapper == null || zapAmountInSats == null) {
    throw InvalidZapRequestException()
}
```
Could you try to zap with long-click and pick one of the predefined amounts? Please let me know what happens in this case.

If doesn't work again, then it could be that some other client has wiped your relays from contacts list (kind 3) and the statement fails on first check.

**Comment by bitcoinuser** [comment]
> Could you try to zap with long-click and pick one of the predefined amounts? Please let me know what happens in this case.

Same problem.

**Comment by bitcoinuser** [comment]
> Can you try to post or reply from the app? Does it work or complains that Network is not configured?

Will test now

**Comment by bitcoinuser** [comment]
> Can you try to post or reply from the app? Does it work or complains that Network is not configured?

Didn't work reply

![Screenshot_2024-02-07-21-25-07-839_net primal android](https://github.com/PrimalHQ/primal-android-app/assets/1178856/01bd7bb7-d390-4afd-9ed8-51a9ce68844a)

**Comment by bitcoinuser** [comment]
Now it's working
