### ISSUE TITLE
When I close Primal it goes back from Latest with Replies to Latest

### ISSUE THREAD

**Issue by bitcoinuser** [PrimalHQ/primal-android-app#83]
Hi,

When I close Primal and open again it goes back from Latest with Replies to Latest. But shouldn't.

Thanks.

**Comment by AleksandarIlic** [comment]
The feed at the top of the feed list is considered to be a default feed. Default feed should open on app start, unless you have exited on Home button.

Some OS versions treat Back as Home exit and in this case the app opens the feed which was last shown.

If none of this helps, let me know what is your top feed and how exactly are you leaving the app. Thanks!
