### ISSUE TITLE
Someone quote some post mine and I didn't see it in Notification

### ISSUE THREAD

**Issue by bitcoinuser** [PrimalHQ/primal-android-app#91]
Hi, 

Someone quote some post mine and I didn't see it in Notification. I see only in the feed. Look the note of LuisSp

https://github.com/PrimalHQ/primal-android-app/assets/1178856/e9023f0c-7fca-4231-9c8c-30630bbecc7c

**Comment by AleksandarIlic** [comment]
Check Primal Web. If its not there then its a backend issue.

**Comment by bitcoinuser** [comment]
Now it's in Primal android and web. I don't know what problem is that delay to show the note in notification.

**Comment by AleksandarIlic** [comment]
Sometimes it takes time for caching service to cache the data for various reasons.
